public with sharing class Constant {
    
    public static final string STATUS_NEW = 'New';
    public static final string CASE_ORIGIN = 'Origin';
    public static final string CASE_SUBJECT_CUSTOMER_TO_AGENCY_INTEGRATION = 'Customer to Agency';
    public static final string SUCCESS = 'Success';
    public static final string STATUS_CODE_400 = '400';
    public static final string STATUS_CODE_200 = '200';
    public static final string ASSOCIATIONCAUSE_TERRITORY2MANUAL = 'Territory2Manual';
    public static final string PARTNER_FUCNTION_Z1 = 'Z1';
    public static final string PARTNER_FUCNTION_Z2 = 'Z2';
    public static final string PARTNER_FUCNTION_ZD = 'ZD';
    public static final string PARTNER_FUCNTION_ZV = 'ZV';
    public static final string PARTNER_FUCNTION_WE = 'WE';
    public static final string ACCOUNT_GROUP_ZOO2 = 'Z002';
    public static final string ACCOUNT_GROUP_ZOO1 = 'Z001';
    public static final string RECORDTYPE_NAME_AGENCY = 'Agency';
    public static final string RECORDTYPE_NAME_HEALTH_CARE_PROVIDER = 'HCO - Healthcare Organization'; //'Health Care Provider';
    public static final string RECORDTYPE_NAME_PRACTITIONER = 'Surgeons';
    public static final string RECORDTYPE_NAME_UNDEFINED = 'Undefined';
    //public static final string RECORDTYPE_NAME_NONE_PRACTITIONER = 'Non-Practitioner';
    public static final string RECORDTYPE_NAME_SURGEON_CONTACT = 'Non - Surgeons';
    public static final string TERRITORY_ARTHREX = 'Arthrex';
    public static final string TERRITORY_ARTHREX_APAC = 'Arthrex APAC';
    public static final string ACCOUNT_TYPE_SPLIT_ACCOUNT = 'Split Account';
    public static final string ACCOUNT_TYPE_REGULAR_ACCOUNT = 'Regular Account';
    public static final string AccountTrigger = 'AccountTrigger';
    public static final string EmailMatrixTrigger = 'EmailMatrixTrigger';
    public static final string CaseParticipantTrigger = 'CaseParticipantTrigger';
    public static final string CaseProcedureTrigger = 'CaseProcedureTrigger';
    public static final string CaseTrigger = 'CaseTrigger';
    // added by chad for 4.4
    public static final string EventTrigger = 'EventTrigger';
    // end added by chad for 4.4
    public static final string ConferenceRepStageTrigger = 'ConferenceRepStageTrigger';
    public static final string ConferenceMemberTrigger = 'ConferenceMemberTrigger';
    public static final string ContactTrigger = 'ContactTrigger';
    public static final string FeedCommentTrigger = 'FeedCommentTrigger';
    public static final string SalesTrigger = 'SalesTrigger';
    public static final string supportCaseAssginment = 'supportCaseAssginment';
    public static final string TicketTrigger = 'TicketTrigger';
    public static final string UserTerritory2AssociationTrigger = 'UserTerritory2AssociationTrigger';
    public static final string UserTrigger = 'UserTrigger';
    public static final string TaskTrigger = 'TaskTrigger';
    public static final string RECORDTYPE_NAME_FELLOWSHIP = 'Fellowship';
    public static final string RECORDTYPE_NAME_RESIDENT = 'Resident';
    // Added by srinivas sattoor on 9.28.2017 for 4.4 CID-000497
    public static final string OPPORTUNITY_RECORDTYPE_NAME_SOS = 'SOS';
    public static final string OPPORTUNITY_RECORDTYPE_NAME_SYSNERGY_INTEGRATION = 'Synergy Integration';
    public static final string OPPORTUNITY_RECORDTYPE_NAME_SYNERGY_SERVICE = 'Synergy Service'; 

}